name: Docker Build

on:
  push:
    branches:
      - testAws
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        id  : branch-name
        uses: tj-actions/branch-names@v7

      - name: install aws-cli
        run: |
          docker run --rm amazon/aws-cli --version

      # - name: Set AWS credentials as environment variables
      #   run: |
      #     echo "Setting up AWS CLI..."
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws configure set default.region us-west-2
      #     echo "AWS CLI configured."

      - name: Configure AWS Credentials for GitHub Role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-west-2
          audience: 1100-aud
          role-to-assume: arn:aws:iam::333300162796:role/s3-test-apt-deb

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Install packages from s3
        run: |
          cd ~
          aws s3 cp s3://1100-bucket/pack_1100.deb . --no-progress
          ls -la

      - name: Checkout SCM
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t vlad1100/test:1100 .
      
      - name: List Docker images
        run: docker images

      # - name: Log into Docker Hub
      #   run: docker login -u vlad1100 -p ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push Docker Image to Docker Hub
  #     #   run: docker push vlad1100/test:1100
  # test:
  #       runs-on: ubuntu-latest
  #       needs: build  # Вказуємо, що ця дія залежить від дії "build"
          
  #       steps:
  #         - name: Abort On Upstream
  #           uses: actions/abort-action@v1
  #           with:
  #             dependencies: build 