name: SAST Report

on:
  push:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run SAST Analysis
        run: npx eslint . --format=json > sast-report.json

      - name: Publish SAST Report
        uses: actions/upload-artifact@v2
        with:
          name: sast-report
          path: sast-report.json
